#name: backend
#services:
#  matcron_api:
#    container_name: backend_api
#    build:
#      context: .
#      dockerfile: Backend/Dockerfile
#    ports:
#      - "8080:8080"
#      - "8081:8081" 
#      - "5225:5225"
#    depends_on:
#      - docker_sqlserver
#
#  docker_sqlserver:
#    container_name: docker_sqlserver
#    build:
#      context: .
#      dockerfile: Backend/db/Dockerfile
#    ports:
#      - "1433:1433"
#    volumes:
#      - sqlserver_data:/var/opt/mssql  # Mounting volume for persistence
#
#volumes:
#  sqlserver_data:  # Declaring the volume


name: backend
services:
  matcron_api:
    container_name: backend_api
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5001:5000"  # Change host port from 5000 to 5001
      - "8080:8080"
      - "8081:8081"
      - "5225:5225"
    depends_on:
      - docker_sqlserver

  docker_sqlserver:
    container_name: docker_sqlserver
    image: mcr.microsoft.com/azure-sql-edge  # Use a prebuilt SQL Server image
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "myPassword1!"  # Update this if necessary
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql  # Mounting volume for persistence

volumes:
  sqlserver_data:  # Declaring the volume
