name: backend
services:
  matcron_api:
    container_name: backend_api
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - docker_sqlserver

  # docker_sqlserver:
  #   container_name: docker_sqlserver
  #   build:
  #     context: .
  #     dockerfile: Backend/db/Dockerfile
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql  #Mounting volume for persistence
  docker_sqlserver:
    container_name: docker_sqlserver
    image: mysql:latest  # Use the official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: "myPassword1!"  # Strong password for root user
      MYSQL_DATABASE: "matcron_db"  # Name of the default database
      MYSQL_USER: "sa"  # Custom MySQL user
      MYSQL_PASSWORD: "userPassword1!"  # Password for the custom user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Mounting volume for persistence

volumes:  # Declaring the volume
  mysql_data: 