# Use the official SQL Server image
FROM mcr.microsoft.com/mssql/server:latest AS sqlserver

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=myPassword1!

# Expose SQL Server port
EXPOSE 1433
