name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push amd64 image
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        push: true
        platforms: linux/amd64
        tags: lee112/matcron:amd6
