name: Build and push Docker image to Docker Hub arm platform

on:
  push:
    branches: [ "development", "testing-workflow-command" ]
  pull_request:
    branches: [ "development" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Arm Docker Image
      working-directory: Backend/
      run: docker buildx build --platform=linux/arm64 -t lee112/matcron:arm -f Backend/Dockerfile --push .

    - name: Build Amd Docker Image
      working-directory: Backend/
      run: docker buildx build --platform=linux/amd64 -t lee112/matcron:amd -f Backend/Dockerfile --push .
